### PR TITLE
added default CMD

### PR DESCRIPTION
**Pull request by allandegnan**
I'd rather not have to specify the command.

### CODE REVIEW

**Comment by vaijab** [comment]
Is that enough for mysql to run?

**Comment by gambol99** [comment]
Looking at the docker entrypoint ... the 'mysqld' is simply an argument rather the actually command line ... Should be fine. One thing does additional arguments to docker run append to CMD or replace? ...if append, probably best to remove the CMD option as you can use it as a generic mysql container no? ... i.e. docker run -ti mysql mysql -h IP etc ..

**Comment by allandegnan** [comment]
The CMD is replaced thus the CMD is the default argument to the ENTRYPOINT when used in this way.

**Comment by vaijab** [comment]
@allandegnan what's the reason you don't want to use `mysqld_safe` instead?

**Comment by PurpleBooth** [comment]
Additional arguments replace not append when you're doing a run

@allandegnan This looks fine to me, but please update the readme too, update the container parameters section and add a new feature point release to the examples (so, it'd be v0.4.0)

@vaijab Lets do moving to `mysqld_safe` in a separate PR, as it's a new feature (although I agree a useful one)

**Comment by PurpleBooth** [comment]
This looks fine to me, but please update the readme too.

**Comment by allandegnan** [comment]
@vaijab I'm not convinced mysqld_safe does anything we care about but I'm not against the idea.

**Comment by vaijab** [comment]
LGTM

**Comment by PurpleBooth** [comment]
LGTM

**Pull request merged**
